# Generated by Django 2.0.6 on 2018-09-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
