# Generated by Django 2.0.6 on 2018-09-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityreview',
            old_name='uni_name',
            new_name='university_name',
        ),
        migrations.RenameField(
            model_name='universityreview',
            old_name='user_name',
            new_name='username',
        ),
    ]
