# Generated by Django 2.1.1 on 2018-09-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityreview',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
