# Generated by Django 2.0.6 on 2018-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20180916_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityreview',
            name='title',
            field=models.CharField(default='example', max_length=200),
            preserve_default=False,
        ),
    ]
