# Generated by Django 2.1.1 on 2018-10-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20181002_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewhelpfulvote',
            name='user',
        ),
    ]
