# Generated by Django 2.1.1 on 2018-09-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20180925_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='university',
            new_name='universities',
        ),
    ]
