# Generated by Django 2.0.6 on 2018-09-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20180926_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityreview',
            name='date_published',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
